# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      exclude: "^(tests/resources/.*)$"
- repo: https://github.com/pyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-expression-complexity
      - flake8-absolute-import
      - flake8-comprehensions
      - flake8-eradicate
      - flake8-simplify
      - flake8-cognitive-complexity
      - flake8-bugbear
